name: bitalarm
description: A cryptocurrency tracker and portfolio app

dependencies:
  sqflite: 0.2.4
  path_provider: 0.2.2
  flutter_charts: 0.1.7
  barcode_scan: 0.0.2
  intl: 0.15.2
  flutter:
    sdk: flutter
  flutter_circular_chart:
    git:
      url: git://github.com/xqwzts/flutter_circular_chart.git
  cupertino_icons: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
   - assets/bitalarm.obj
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  fonts:
    - family: 'Roboto Mono'
      fonts:
        - asset: assets/fonts/Roboto_Mono/RobotoMono-Light.ttf
          weight: 100
        - asset: assets/fonts/Roboto_Mono/RobotoMono-Regular.ttf
          weight: 300
        - asset: assets/fonts/Roboto_Mono/RobotoMono-Medium.ttf
          weight: 400
        - asset: assets/fonts/Roboto_Mono/RobotoMono-Bold.ttf
          weight: 700

